[tool.ruff]
# exclude = [".venv", "venv", "pyproject.toml"]
include = ["*.py"]
src = ["src", "src/sb", "src/utils"]
fix = true
indent-width = 4
line-length = 80

[tool.ruff.lint]
ignore = ["E402", "E203"]

[tool.ruff.format]
skip-magic-trailing-comma = true
