[tool.ruff]
# exclude = [".venv", "venv", "pyproject.toml"]
include = ["*.py"]
src = ["src", "src/sb", "src/utils"]
fix = true
indent-width = 4
line-length = 80

[tool.ruff.lint]
ignore = ["E402", "E203"]

[tool.ruff.format]
skip-magic-trailing-comma = true

[tool.pyrefly]
project_includes = ["src", "src/sb", "src/utils"]

[tool.pyrefly.errors]
annotation-mismatch = false
assert-type = false
async-error = false
bad-argument-count = false
bad-argument-type = false
bad-assignment = false
bad-class-definition = false
bad-function-definition = false
bad-keyword-argument = false
bad-override = false
bad-return = false
bad-specialization = false
bad-unpacking = false
delete-error = false
import-error = false
index-error = false
internal-error = false
invalid-annotation = false
invalid-argument = false
invalid-inheritance = false
invalid-literal = false
invalid-overload = false
invalid-param-spec = false
invalid-super-call = false
invalid-syntax = false
invalid-type-var = false
invalid-type-var-tuple = false
invalid-yield = false
match-error = false
missing-argument = false
missing-attribute = false
missing-module-attribute = false
no-access = false
no-matching-overload = false
not-a-type = false
not-callable = false
not-iterable = false
parse-error = false
read-only = false
reveal-type = false
type-alias-error = false
typed-dict-key-error = false
unbound-name = false
unexpected-keyword = false
unknown-name = false
unsupported-operand = false
unsupported = false
